name: liquid
description: Library to build User Interfaces [Virtual DOM]
version: 0.2.0
author: Boris Kaul <localvoid@gmail.com>
homepage: https://github.com/localvoid/liquid
environment:
  sdk: '>=1.6.0'
dependencies:
  vdom:
    git: git://github.com/localvoid/vdom.git
  dom_scheduler:
    git: git://github.com/localvoid/dom_scheduler.git
dev_dependency:
  browser: any
