name: liquid
description: Library to build User Interfaces [Virtual DOM]
version: 0.1.3
author: Boris Kaul <localvoid@gmail.com>
homepage: https://github.com/localvoid/liquid
environment:
  sdk: '>=1.6.0'
dependencies:
  vdom: '>=0.5.1 <0.6.0'
  collection: '>=1.0.0 <2.0.0'
dev_dependency:
  browser: any
