name: liquid
description: Library to build User Interfaces [Virtual DOM]
version: 0.0.1
author: Boris Kaul <localvoid@gmail.com>
homepage: https://github.com/localvoid/liquid
environment:
  sdk: '>=1.6.0'
dependencies:
  browser: any
  vdom: '>=0.4.0+1 <0.5.0'
  collection: '>=1.0.0 <2.0.0'
dependency_overrides:
  vdom:
    path: ../vdom